# Generated by Django 5.0.4 on 2026-05-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxygenreading',
            name='relay1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oxygenreading',
            name='relay2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oxygenreading',
            name='relay3',
            field=models.BooleanField(default=False),
        ),
    ]
