# Generated by Django 5.0.4 on 2026-05-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen_app', '0002_oxygenreading_relay1_oxygenreading_relay2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxygenreading',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oxygenreading',
            name='temp_air',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
