# Generated by Django 5.0.4 on 2026-07-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxygen_app', '0003_oxygenreading_humidity_oxygenreading_temp_air'),
    ]

    operations = [
        migrations.AddField(
            model_name='oxygenreading',
            name='pzem_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oxygenreading',
            name='pzem_energy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oxygenreading',
            name='pzem_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oxygenreading',
            name='pzem_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oxygenreading',
            name='rpm1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oxygenreading',
            name='rpm2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oxygenreading',
            name='rpm3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
